definitions:
  controllers.customerInput:
    properties:
      name:
        type: string
      nik:
        type: string
      phone_number:
        type: string
    required:
    - name
    - nik
    - phone_number
    type: object
  models.Customer:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      nik:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /customer:
    get:
      description: Get a list of customer.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Customer'
            type: array
      summary: Get All Customer.
      tags:
      - Customer
    post:
      description: Create a new customer.
      parameters:
      - description: The body to create a new Customer
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.customerInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customer'
      summary: Create New Customer.
      tags:
      - Customer
  /customer/{id}:
    delete:
      description: Delete a customer by id.
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Delete one customer.
      tags:
      - Customer
    patch:
      description: Update customer by id.
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      - description: The body to update an Customer
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.customerInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customer'
      summary: Update Customer.
      tags:
      - Customer
swagger: "2.0"
